UPDATE payments SET singer_id = 11 WHERE singer_id = 91;
DELETE FROM singers WHERE id = 91;
UPDATE payments SET singer_id = 24 WHERE singer_id = 112;
DELETE FROM singers WHERE id = 112;
UPDATE payments SET singer_id = 185 WHERE singer_id = 660;
DELETE FROM singers WHERE id = 660;
UPDATE payments SET singer_id = 186 WHERE singer_id = 661;
DELETE FROM singers WHERE id = 661;
UPDATE payments SET singer_id = 191 WHERE singer_id = 193;
DELETE FROM singers WHERE id = 193;
UPDATE payments SET singer_id = 191 WHERE singer_id = 745;
DELETE FROM singers WHERE id = 745;
UPDATE payments SET singer_id = 205 WHERE singer_id = 768;
DELETE FROM singers WHERE id = 768;
UPDATE payments SET singer_id = 206 WHERE singer_id = 769;
DELETE FROM singers WHERE id = 769;
UPDATE payments SET singer_id = 210 WHERE singer_id = 746;
DELETE FROM singers WHERE id = 746;
UPDATE payments SET singer_id = 212 WHERE singer_id = 213;
DELETE FROM singers WHERE id = 213;
UPDATE payments SET singer_id = 212 WHERE singer_id = 715;
DELETE FROM singers WHERE id = 715;
UPDATE payments SET singer_id = 214 WHERE singer_id = 714;
DELETE FROM singers WHERE id = 714;
UPDATE payments SET singer_id = 609 WHERE singer_id = 627;
DELETE FROM singers WHERE id = 627;