-- ════════════════════════════════════════════════════════════════════════
-- Best Artist Voting — D1 Seed Data
-- Run AFTER schema.sql. Images are left empty; fetch them separately
-- using the /api/wiki-bio or /api/proxy-image endpoints, or the
-- backfill-wiki-images script.
-- ════════════════════════════════════════════════════════════════════════

INSERT INTO singers (name, country, genre) VALUES
('The Beatles','United Kingdom','Rock'),
('Michael Jackson','USA','Pop'),
('Elvis Presley','USA','Rock & Roll'),
('Queen / Freddie Mercury','United Kingdom','Rock'),
('Madonna','USA','Pop'),
('The Rolling Stones','United Kingdom','Rock'),
('Taylor Swift','USA','Pop'),
('Ed Sheeran','United Kingdom','Pop'),
('Beyoncé','USA','R&B'),
('Rihanna','Barbados','Pop/R&B'),
('Adele','United Kingdom','Soul/Pop'),
('Eminem','USA','Hip-Hop'),
('Drake','Canada','Hip-Hop'),
('Coldplay','United Kingdom','Alternative Rock'),
('Pink Floyd','United Kingdom','Progressive Rock'),
('Led Zeppelin','United Kingdom','Hard Rock'),
('ABBA','Sweden','Pop'),
('Mariah Carey','USA','Pop/R&B'),
('Whitney Houston','USA','R&B'),
('Céline Dion','Canada','Pop'),
('Bruno Mars','USA','Pop/Funk'),
('Ariana Grande','USA','Pop'),
('Billie Eilish','USA','Alt-Pop'),
('The Weeknd','Canada','R&B/Pop'),
('Justin Bieber','Canada','Pop'),
('Katy Perry','USA','Pop'),
('Lady Gaga','USA','Pop'),
('Shakira','Colombia','Latin Pop'),
('Jennifer Lopez','USA','Latin Pop'),
('Dua Lipa','United Kingdom','Pop'),
('Harry Styles','United Kingdom','Pop'),
('Sia','Australia','Pop'),
('Kanye West','USA','Hip-Hop'),
('Jay-Z','USA','Hip-Hop'),
('Kendrick Lamar','USA','Hip-Hop'),
('Travis Scott','USA','Hip-Hop'),
('Post Malone','USA','Hip-Hop/Pop'),
('The Chainsmokers','USA','EDM'),
('Calvin Harris','Scotland','EDM'),
('David Guetta','France','EDM'),
('Avicii','Sweden','EDM'),
('Alan Walker','Norway','EDM'),
('Imagine Dragons','USA','Pop Rock'),
('Maroon 5','USA','Pop Rock'),
('OneRepublic','USA','Pop Rock'),
('Linkin Park','USA','Nu Metal'),
('Green Day','USA','Punk Rock'),
('Nirvana','USA','Grunge'),
('Metallica','USA','Heavy Metal'),
('Guns N'' Roses','USA','Hard Rock'),
('AC/DC','Australia','Hard Rock'),
('Bon Jovi','USA','Rock'),
('U2','Ireland','Rock'),
('Red Hot Chili Peppers','USA','Funk Rock'),
('Radiohead','United Kingdom','Alternative'),
('Oasis','United Kingdom','Britpop'),
('Blur','United Kingdom','Britpop'),
('Arctic Monkeys','United Kingdom','Indie Rock'),
('Foo Fighters','USA','Rock'),
('Muse','United Kingdom','Alternative Rock'),
('Bob Marley','Jamaica','Reggae'),
('Stevie Wonder','USA','Soul'),
('Aretha Franklin','USA','Soul'),
('James Brown','USA','Funk/Soul'),
('Tina Turner','USA','Rock/Soul'),
('Prince','USA','Funk/Rock'),
('David Bowie','United Kingdom','Art Rock'),
('Elton John','United Kingdom','Pop Rock'),
('Billy Joel','USA','Pop Rock'),
('Rod Stewart','United Kingdom','Rock'),
('Phil Collins','United Kingdom','Pop Rock'),
('George Michael','United Kingdom','Pop'),
('Lionel Richie','USA','Pop/Soul'),
('Quincy Jones','USA','Producer/Artist'),
('Frank Sinatra','USA','Jazz/Traditional Pop'),
('Nat King Cole','USA','Jazz'),
('Halsey','USA','Alt-Pop'),
('Melanie Martinez','USA','Alt-Pop'),
('Twenty One Pilots','USA','Alt-Pop'),
('Panic! At The Disco','USA','Pop Rock'),
('Fall Out Boy','USA','Pop Punk'),
('Paramore','USA','Pop Punk'),
('My Chemical Romance','USA','Emo Rock'),
('All Time Low','USA','Pop Punk'),
('5 Seconds of Summer','Australia','Pop Rock'),
('Charlie Puth','USA','Pop'),
('James Arthur','United Kingdom','Pop'),
('Sam Smith','United Kingdom','Pop'),
('Lewis Capaldi','Scotland','Pop'),
('Amy Winehouse','United Kingdom','Soul'),
('Adele Adkins','United Kingdom','Soul'),
('Duffy','Wales','Soul'),
('Paloma Faith','United Kingdom','Soul'),
('Jessie J','United Kingdom','Pop'),
('Ellie Goulding','United Kingdom','Pop'),
('Rita Ora','United Kingdom','Pop'),
('Zara Larsson','Sweden','Pop'),
('Tove Lo','Sweden','Pop'),
('Robyn','Sweden','Pop'),
('Avril Lavigne','Canada','Pop Punk'),
('Alanis Morissette','Canada','Alt-Rock'),
('Sheryl Crow','USA','Rock'),
('Michelle Branch','USA','Pop Rock'),
('Vanessa Carlton','USA','Pop'),
('Alicia Keys','USA','R&B'),
('John Legend','USA','R&B'),
('Usher','USA','R&B'),
('Chris Brown','USA','R&B'),
('Ne-Yo','USA','R&B'),
('Mario','USA','R&B'),
('Trey Songz','USA','R&B'),
('The Weeknd Abel','Canada','R&B'),
('SZA','USA','R&B'),
('Doja Cat','USA','Pop/Rap'),
('Nicki Minaj','Trinidad/USA','Rap'),
('Cardi B','USA','Rap'),
('Megan Thee Stallion','USA','Rap'),
('Ice Spice','USA','Rap'),
('Lil Wayne','USA','Rap'),
('Future','USA','Rap'),
('21 Savage','UK/USA','Rap'),
('A$AP Rocky','USA','Rap'),
('Tyler, The Creator','USA','Hip-Hop'),
('Childish Gambino','USA','Hip-Hop'),
('J. Cole','USA','Hip-Hop'),
('Nas','USA','Hip-Hop'),
('The Notorious B.I.G.','USA','Hip-Hop'),
('2Pac','USA','Hip-Hop'),
('Snoop Dogg','USA','Hip-Hop'),
('Dr. Dre','USA','Hip-Hop'),
('50 Cent','USA','Hip-Hop'),
('DMX','USA','Hip-Hop'),
('Missy Elliott','USA','Hip-Hop'),
('Lauryn Hill','USA','R&B/Hip-Hop'),
('Outkast','USA','Hip-Hop'),
('Andre 3000','USA','Hip-Hop'),
('Bad Bunny','Puerto Rico','Reggaeton'),
('J Balvin','Colombia','Reggaeton'),
('Maluma','Colombia','Latin Pop'),
('Ozuna','Puerto Rico','Reggaeton'),
('Daddy Yankee','Puerto Rico','Reggaeton'),
('Luis Fonsi','Puerto Rico','Latin Pop'),
('Enrique Iglesias','Spain','Latin Pop'),
('Ricky Martin','Puerto Rico','Latin Pop'),
('Marc Anthony','USA','Salsa'),
('Selena Quintanilla','Mexico','Tejano'),
('Rosalia','Spain','Flamenco Pop'),
('Karol G','Colombia','Reggaeton'),
('Peso Pluma','Mexico','Corridos'),
('Feid','Colombia','Reggaeton'),
('BTS','South Korea','K-Pop'),
('BLACKPINK','South Korea','K-Pop'),
('TWICE','South Korea','K-Pop'),
('Stray Kids','South Korea','K-Pop'),
('EXO','South Korea','K-Pop'),
('SEVENTEEN','South Korea','K-Pop'),
('NCT 127','South Korea','K-Pop'),
('TXT (Tomorrow X Together)','South Korea','K-Pop'),
('aespa','South Korea','K-Pop'),
('ITZY','South Korea','K-Pop'),
('(G)I-DLE','South Korea','K-Pop'),
('Red Velvet','South Korea','K-Pop'),
('IU','South Korea','K-Pop'),
('PSY','South Korea','K-Pop'),
('Taeyeon','South Korea','K-Pop'),
('Jungkook','South Korea','K-Pop'),
('Jimin','South Korea','K-Pop'),
('Lisa','Thailand/Korea','K-Pop'),
('Jennie','South Korea','K-Pop'),
('Rosé','Australia/Korea','K-Pop'),
('Jisoo','South Korea','K-Pop'),
('NewJeans','South Korea','K-Pop'),
('IVE','South Korea','K-Pop'),
('LE SSERAFIM','South Korea','K-Pop'),
('Siti Nurhaliza','Malaysia','Pop'),
('Yuna','Malaysia','R&B/Pop'),
('Faizal Tahir','Malaysia','Pop Rock'),
('Anuar Zain','Malaysia','Pop'),
('Hafiz Suip','Malaysia','Pop'),
('Stacy','Malaysia','Pop'),
('Aznil Nawawi','Malaysia','Pop'),
('M. Nasir','Malaysia','Folk Rock'),
('Sheila Majid','Malaysia','Jazz Pop'),
('Ziana Zain','Malaysia','Pop'),
('Amy Search','Malaysia','Rock'),
('Awie','Malaysia','Rock'),
('Ella','Malaysia','Rock'),
('Ning Baizura','Malaysia','Pop'),
('Jaclyn Victor','Malaysia','Pop/Soul'),
('Res2','Malaysia','Pop'),
('Agnes Mo','Indonesia','Pop'),
('Rossa','Indonesia','Pop'),
('Agnez Mo','Indonesia','Pop'),
('Raisa','Indonesia','Pop'),
('Isyana Sarasvati','Indonesia','Pop'),
('Tulus','Indonesia','Pop'),
('Glenn Fredly','Indonesia','R&B'),
('Sherina Munaf','Indonesia','Pop'),
('Sarah Geronimo','Philippines','Pop'),
('Regine Velasquez','Philippines','Pop'),
('Lea Salonga','Philippines','Musical Theatre'),
('Moira Dela Torre','Philippines','Pop'),
('Ben&Ben','Philippines','Folk Pop'),
('SB19','Philippines','P-Pop'),
('Charice Pempengco','Philippines','Pop'),
('Arnel Pineda','Philippines','Rock'),
('Namewee','Malaysia','Hip-Hop'),
('Insomniacks','Malaysia','Pop'),
('K-Clique','Malaysia','Hip-Hop'),
('Bunga Citra Lestari','Indonesia','Pop'),
('Andra and The Backbone','Indonesia','Rock'),
('Noah','Indonesia','Pop Rock'),
('Peterpan','Indonesia','Pop Rock'),
('Dewa 19','Indonesia','Rock'),
('Slank','Indonesia','Rock'),
('Sheila On 7','Indonesia','Pop Rock');
