// Generated by Wrangler by running `wrangler types`

interface Env {
	CURRENCY: "usd";
	STRIPE_PUBLISHABLE_KEY: "";
	PAYPAL_CLIENT_ID: "";
	COUNTRY_DEFAULT: "Global";
	DB: D1Database;
	ASSETS: Fetcher;
}
